### PR TITLE
General polish with stuff taken from PR #87

### PR DESCRIPTION
**Pull request by SuperGamer18**
https://github.com/SuperGamer18/RetroAchievements-docs/blob/updates/docs/developer-docs/unsupported-emulators-and-cores.md I've noticed that this doc was based on an old version, before I made PR #87. What I've done here is "port" over most of the stuff I added and/or changed mostly using [this commit](https://github.com/SuperGamer18/RetroAchievements-docs/blob/a08f95da829da01a5891f61d03aa5d5ee5b257fe/docs/general/emulator-support-and-issues.md) as a base (it's basically almost everything that I did before @suspect15 asked me to delete all of the unsupported emulators). I've obviously left out stuff such as informal messages and the likes. I've also added some more information and updated it (eg PicoDrive DOES support turning pages). As usual, I'll appreciate any feedback you guys give ;3

### CODE REVIEW

**Comment by wescopeland** [comment]
I'm not comfortable with this being merged unless an emulator/integration maintainer weighs in first.

@Jamiras @Sanaki Do you have any feedback you'd like to add on these changes?

**Comment by Jamiras** [comment]
When I first got the ping for this, I was curious why you thought I'd be of any use for a Polish translation.

> I'm not comfortable with this being merged unless an emulator/integration maintainer weighs in first.
> 
> @Jamiras @Sanaki Do you have any feedback you'd like to add on these changes?

It looks like there's some additional information being added, and a lot of prose being changed, but as long as the data is present, I'm not terribly concerned about the formatting. With one exception: I would recommend keeping the dates as "D Mon YEAR", as that's generally a more friendly format for an international userbase.

**Comment by SuperGamer18** [comment]
I am planning on making a Spanish translation of this doc, since we're talking about languages.

**Comment by SuperGamer18** [comment]
Done. All that should be left is the Spanish translation, which I'll probably leave for another PR.

**Comment by gboquizosanchez** [comment]
> Done. All that should be left is the Spanish translation, which I'll probably leave for another PR.

Please, include me in that PR.

**Comment by SuperGamer18** [comment]
Alright 👍

**Comment by televandalist** [comment]
There's a merge conflict since unsupported emulators and cores were moved to their own page - I'm fine with merging after that gets resolved

**Comment by wescopeland** [comment]
Hi @SuperGamer18! We are happy to take these changes, but it appears there's a merge conflict in the branch that needs to be resolved.

**Comment by SuperGamer18** [comment]
Hey Wes! Tele already reminded me of that, but thanks anyways :3

**Comment by SuperGamer18** [comment]
I'm sorry for not being able to deliver the changes on time. I wasn't aware of the split until not-so recently and I haven't found any free time to dedicate to this. I also have to find the last commit made before this split. I'll try better next time!

**Comment by wescopeland** [comment]
There is nothing to apologize for :) Life gets busy. You are always welcome to contribute as your schedule allows!

**Pull request closed without merging**
