### PR TITLE
docs: establishing spanish translations

### PR DESCRIPTION
**Pull request by gboquizosanchez**
This PR has important changes.  

- [x] Docs have been sync with English in general folder. 
- [x] All navbar links have been re-translated.
- [x] How RA works has been fully translated.
- [x] Finally I have found a good term for rich presence. It will be "presencia enriquecida". I have taken this from RetroArch.
- [x] How to become a developer has been reviewed and some parts re-translated.
- [x] "Emblema" has been changed to "insignia" in my previous translations.

Pending things

- [ ] Anchors. Related with #105.

### CODE REVIEW

**Comment by wescopeland** [comment]
Lots of improvements here - thanks! Would you like to wait on the anchors issue, or would you prefer to see this merged and figure the anchors stuff out later?

**Comment by SuperGamer18** [comment]
I would love to collaborate on this, I know that a decent amount of people on RA speak Spanish as their primary/native language (including me) and taking care of this situation, at least for the RADocs (as of now) is an excellent idea. Right now, I'm waiting for Wes to approve a new page I've made for issue #94 and since you seem to be the only guy apart from me who speaks Spanish, I would like to make a translation for that page (after it gets approved of course) and let you check it. If you want to see the PR, it's #104.

**Comment by gboquizosanchez** [comment]
> Lots of improvements here - thanks! Would you like to wait on the anchors issue, or would you prefer to see this merged and figure the anchors stuff out later?

I think we can merge this, anchors are a mess right now, It's necessary to check it out in several places. So, we can do it later!

**Comment by gboquizosanchez** [comment]
> I would love to collaborate on this, I know that a decent amount of people on RA speak Spanish as their primary/native language (including me) and taking care of this situation, at least for the RADocs (as of now) is an excellent idea. Right now, I'm waiting for Wes to approve a new page I've made for issue #94 and since you seem to be the only guy apart from me who speaks Spanish, I would like to make a translation for that page (after it gets approved of course) and let you check it. If you want to see the PR, it's #104.

Sure, of course, I'll be glad to check it out your translation ;) We can make some discussions about terms, styles, translations and other kind of things to have a "common way" to make the "re-translation" and establish a good style in the Spanish docs.

**Review by wescopeland — APPROVED** [review]

**Pull request merged**
